name: LibsHungergames
main: me.libraryaddict.Hungergames.Hungergames
author: libraryaddict
version: ${project.version}
website: http://www.spigotmc.org/resources/libs-hungergames.55/
load: startup
softdepend: [LibsDisguises, Vault]